# Generated by Django 4.1.7 on 2023-05-12 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0003_book_cover_book_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The Review text.')),
                ('rating', models.IntegerField(help_text='The the reviewer has given.')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date and time the review was created.')),
                ('date_edited', models.DateTimeField(help_text='The date and time the review was last edited.', null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the post.', max_length=70)),
                ('publication_date', models.DateField(verbose_name='Date the post was published.')),
                ('isbn', models.CharField(max_length=20, verbose_name='ISBN number of the post.')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='post_covers/')),
                ('sample', models.FileField(blank=True, null=True, upload_to='post_samples/')),
            ],
        ),
        migrations.CreateModel(
            name='postContributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AUTHOR', 'Author'), ('EDITOR', 'Editor')], max_length=20, verbose_name='The role this contributor had in the post.')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.contributor')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.post')),
            ],
        ),
        migrations.RemoveField(
            model_name='bookcontributor',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookcontributor',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.RemoveField(
            model_name='review',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookContributor',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='post',
            name='contributors',
            field=models.ManyToManyField(through='reviews.postContributor', to='reviews.contributor'),
        ),
        migrations.AddField(
            model_name='post',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.publisher'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(help_text='The post that this review is for.', on_delete=django.db.models.deletion.CASCADE, to='reviews.post'),
        ),
    ]
