# Generated by Django 4.1.7 on 2023-05-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_tag_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
    ]
