# Generated by Django 4.1.7 on 2023-05-13 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_comment_content_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcontributor',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='postcontributor',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publisher',
        ),
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reviews.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='numOfLikes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.DeleteModel(
            name='postContributor',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
